/*
 * Copyright 2026 Haulmont.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.jmix.reports.annotation;

import io.jmix.reports.entity.ReportOutputType;
import io.jmix.reports.entity.ReportTemplate;

import java.lang.annotation.*;

/**
 * Defines a template - element of the report structure.
 * This annotation can be used several times on the report class if it has several templates.
 * Additional associated logic can be declared by declaring a method annotated with {@link TemplateDelegate}.
 * <br/>
 * Model object is {@link ReportTemplate}.
 * @see ReportDef
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Repeatable(RepeatableTemplateDef.class)
public @interface TemplateDef {

    /**
     * Unique template code. Use it when referring to this template programmatically.
     */
    String code();

    /**
     * Whether this template should be automatically used by document generation,
     *   unless user explicitly specifies other one.
     */
    boolean isDefault() default false;

    /**
     * Type of the output, it determines kind of the output content generated by reporting engine.
     * Output type should be consistent with the template file type.
     */
    ReportOutputType outputType();

    /**
     * Whether the user should be able to choose the output type of report at runtime in UI.
     */
    boolean alterableOutput() default false;

    /**
     * Additional parameters for custom output document rendering.
     */
    CustomTemplateParameters custom() default @CustomTemplateParameters();

    /**
     * Optional file name pattern which will be used to generate the file name for the produced report.
     * It can either be a constant string or contain a report parameter as a variable, for example, <code>${header.authorName}.xlsx</code>.
     */
    String outputNamePattern() default "";

    /**
     * Path to the file located on the classpath that contains template content.
     * Template files are typically put to the <code>resources</code> source root of the same module.
     */
    String filePath() default "";

    /**
     * Table template definition for {@link ReportOutputType#TABLE} output type.
     */
    TemplateTableDef table() default @TemplateTableDef(bands = {});

    /**
     * Template engine used to process contents of text templates.
     * Used for HTML template files (with various output types).
     */
    TemplateMarkupEngine templateEngine() default TemplateMarkupEngine.FREEMARKER;

}
