mutation {
    upsert_scr_DatatypesTestEntity(datatypesTestEntity:{
        bigDecimalAttr: 1234
        compositionO2Oattr: {
            name: "test"
            quantity: -10
        }
    }){
        id
        compositionO2Oattr{
            name
            quantity
        }
    }
}