swagger: '2.0'

info:
  version: "6.10"
  title: CUBA Platform Reports REST API
  description: |

    ## General Overview

    CUBA Platform Reports REST API provides the following functionality:

    * Getting list of avaliable reports
    * Getting report metadata (parameters, templates)
    * Getting report group details
    * Execution of report

    The Reports REST API is available at the URL `/rest/reports/v1` in the web module, e.g. `http://localhost:8080/app/rest/reports/v1/report`

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################

basePath: /app/rest/reports/v1
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  reportIdParam:
    name: reportId
    in: path
    type: string
    description: Report identifier
    required: true
    default: ""
  groupIdParam:
    name: groupId
    in: path
    type: string
    description: Report Group identifier
    required: true
    default: ""
  entityJsonParam:
    name: entityJson
    description: JSON object with the entity
    in: body
    schema:
      "$ref": "#/definitions/entity"
################################################################################
#                                   Definitions                                #
################################################################################
definitions:
  error:
    type: object
    properties:
      error:
        type: string
        description: Error message
      details:
        type: string
        description: Detailed error description

  report:
    type: object
    properties:
      id:
        type: string
        description: Report id
      name:
        type: string
        description: Report name
      code:
        type: string
        description: Report code
      group:
        type: string
        description: Group id

  reportFull:
    type: object
    properties:
      id:
        type: string
        description: Report id
      name:
        type: string
        description: Report name
      code:
        type: string
        description: Report code
      group:
        type: string
        description: Group id
      inputParameters:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            alias:
              type: string
            type:
              type: string
              enum:
                - DATE
                - TEXT
                - ENTITY
                - BOOLEAN
                - NUMERIC
                - ENTITY_LIST
                - ENUMERATION
                - DATETIME
                - TIME
            required:
              type: boolean
            hidden:
              type: boolean
            entityMetaClass:
              type: string
              example: sec$User
              description: |
                For ENTITY, ENTITY_LIST type there will be a entity metaclass name here
            enumerationClass:
              type: string
              description: |
                For ENUMERATION type there will be a java class for enumeration here
            defaultValue:
              type: string
              description: |
                Default value of parameter in string form
      templates:
        type: array
        items:
          type: object
          properties:
            code:
              type: string
            outputType:
              type: string
              enum:
                - XLS
                - DOC
                - PDF
                - HTML
                - DOCX
                - XLSX
                - CUSTOM
                - CSV
  runObject:
    type: object
    properties:
      template:
        type: string
        description: template code
      attachment:
        type: boolean
      parameters:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              description:
            value:
              type: string
            values:
              type: array
              items:
                type: string

  group:
    type: object
    properties:
      id:
        type: string
        description: Group id
      title:
        type: string
        description: Group title
      code:
        type: string
        description: Group code

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Reports list
  - name: Report
  - name: Run report

################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    tokenUrl: http://localhost:8080/app/rest/v2/oauth/token
    scopes:
      rest-api: use REST API
  tokenEndpointBasic:
    type: basic

security:
  - oauth2:
    - rest-api

################################################################################
#                                   Paths                                      #
################################################################################
paths:
############################### Entities ###################################
  /report:
    get:
      tags:
        - Reports list
      summary: Get a list of reports
      description: |
        Gets a list of reports
      responses:
        200:
          description: Success. The list of reports is returned in the response body.
          schema:
            type: array
            items:
              "$ref": "#/definitions/report"
        403:
          description: Forbidden. The user doesn't have permissions to read the report
          schema:
            $ref: '#/definitions/error'

  /report/{reportId}:
    parameters:
      - $ref: '#/parameters/reportIdParam'
    get:
      tags:
        - Report
      summary: Get a single report by id
      description: |
        Gets a single report by identifier
      responses:
        200:
          description: Success. The report is returned in the response body.
          schema:
            $ref: '#/definitions/reportFull'
        403:
          description: Forbidden. The user doesn't have permissions to read the report
          schema:
            $ref: '#/definitions/error'

  /group/{groupId}:
    parameters:
      - $ref: '#/parameters/groupIdParam'
    get:
      tags:
        - Group
      summary: Get a single group by id
      description: |
        Gets a single group by identifier
      responses:
        200:
          description: Success. The group is returned in the response body.
          schema:
            $ref: '#/definitions/group'
        403:
          description: Forbidden. The user doesn't have permissions to read the report group
          schema:
            $ref: '#/definitions/error'

  /run/{reportId}:
     parameters:
      - $ref: '#/parameters/reportIdParam'
     post:
      tags:
        - Run report
      summary: Run report
      description: |
        Runs report and returns report document. The method expects a JSON with selected parameters and report template
        in the request body
      parameters:
        - name: runObject
          in: body
          schema:
            "$ref": "#/definitions/runObject"
      responses:
        200:
          description: Success. The file contents is returned in the response body.
        400:
          description: Bad request. For example, the condition value cannot be parsed.
          schema:
            $ref: '#/definitions/error'
        403:
          description: Forbidden. The user doesn't have permissions to read the report
          schema:
            $ref: '#/definitions/error'

############################### Documentation #################################
  /docs/swagger.{format}:
    get:
      tags:
        - Documentation
      summary: Get the Reports REST API swagger documentation
      description: Gets the swagger documentation in the JSON or YAML formats
      parameters:
        - name: format
          in: path
          type: string
          description: swagger format (json or yaml)
          default: yaml
      responses:
        200:
          description: Success