/*
 * Copyright (c) 2008-2019 Haulmont.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.jmix.core.metamodel.annotation;

import java.lang.annotation.*;

/**
 * Defines DDL code to be generated by tooling for entity attributes.
 */
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
@Repeatable(DdlByDbms.class)
public @interface Ddl {

    /**
     * DBMS type for which to apply this DDL code. If not specified, this DDL is the default for any DBMS.
     * <p>Studio recognizes the following values:
     * <ul>
     *     <li>hsql</li>
     *     <li>postgres</li>
     *     <li>mysql</li>
     *     <li>mssql</li>
     *     <li>mssql-2005</li>
     *     <li>mssql-2008</li>
     *     <li>mssql-2012</li>
     *     <li>oracle</li>
     * </ul>
     */
    String dbms() default "";

    /**
     * DDL code.
     */
    String value();
}
