package io.jmix.oidc.user;

import org.springframework.security.oauth2.core.oidc.OidcIdToken;
import org.springframework.security.oauth2.core.oidc.OidcUserInfo;
import org.springframework.security.oauth2.core.oidc.user.OidcUser;

import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;
import java.util.Map;

/**
 * Mapped superclass to be extended by JPA entity that stores user information. Extend the {@code User} entity class
 * generated by Jmix Studio in order to make it work with jmix-oidc add-on.
 */
@MappedSuperclass
public abstract class JmixOidcUserEntity implements JmixOidcUser, HasOidcUserDelegate {

    @Transient
    protected OidcUser delegate;

    public OidcUser getDelegate() {
        return delegate;
    }

    public void setDelegate(OidcUser delegate) {
        this.delegate = delegate;
    }

    @Override
    public Map<String, Object> getClaims() {
        return delegate.getClaims();
    }

    @Override
    public OidcUserInfo getUserInfo() {
        return delegate.getUserInfo();
    }

    @Override
    public OidcIdToken getIdToken() {
        return delegate.getIdToken();
    }

    @Override
    public Map<String, Object> getAttributes() {
        return delegate.getAttributes();
    }

    @Override
    public String getName() {
        return delegate.getName();
    }
}
