query{
    permissions{
        entities{
            target
            value
        }
        entityAttributes{
            target
            value
        }
        specifics{
            target
            value
        }
    }
}