/*
 * Copyright 2026 Haulmont.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package xlsx

import io.jmix.reports.entity.ReportTemplate
import io.jmix.reports.yarg.formatters.factory.FormatterFactoryInput
import io.jmix.reports.yarg.formatters.impl.StreamingXlsxFormatter
import io.jmix.reports.yarg.formatters.impl.streaming.StreamingBandFeed
import io.jmix.reports.yarg.structure.BandData
import io.jmix.reports.yarg.structure.ReportOutputType
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import spock.lang.IgnoreIf
import spock.lang.Specification

import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong

/**
 * Phase-2 contrast case for {@link StreamingLargeXlsxReportGenerationTest}: the hot band's rows are
 * GENERATED by a feed iterator instead of being materialized as 500k {@link BandData} children, so the
 * retained heap no longer scales with the row count on the input side either. The default bound is
 * accordingly tighter than the Phase-1 test's (192 MB vs 512 MB; Phase 1 measured ~122 MB retained WITH
 * the materialized input tree).
 *
 * <p>Runs only with {@code -PincludeSlowTests=true}. Scale and bound overridable via
 * {@code REPORT_STRESS_ROWS} / {@code REPORT_STRESS_COLUMNS} / {@code REPORT_STRESS_HEAP_BOUND_MB}.
 */
@IgnoreIf({ env['slowTests'] != 'true' })
class StreamingFeedLargeXlsxReportGenerationTest extends Specification {

    private static final Logger log = LoggerFactory.getLogger(StreamingFeedLargeXlsxReportGenerationTest)

    private static final String BAND_NAME = "Data"

    private static final int COLUMNS = resolveInt("report.stress.columns", "REPORT_STRESS_COLUMNS", 200)
    private static final int ROWS = resolveInt("report.stress.rows", "REPORT_STRESS_ROWS", 500_000)
    private static final int HEAP_BOUND_MB = resolveInt("report.stress.heap.bound.mb", "REPORT_STRESS_HEAP_BOUND_MB", 192)

    private static int resolveInt(String systemProperty, String environmentVariable, int defaultValue) {
        def value = System.getProperty(systemProperty) ?: System.getenv(environmentVariable)
        return value != null ? Integer.parseInt(value) : defaultValue
    }

    def "streams a large xlsx report from a generated feed within a bounded heap"() {
        given: "a single-band template and a row-generating feed; nothing is materialized up front"
            log.info("Streaming XLSX from feed: {} columns x {} rows = {} cells, heap bound {} MB",
                    COLUMNS, ROWS, ((long) COLUMNS) * ROWS, HEAP_BOUND_MB)

            def template = new ReportTemplate()
            template.setContent(LargeXlsxReportGenerationTest.buildTemplate(COLUMNS))

            Map<String, Object> rowData = [:]
            for (int c = 0; c < COLUMNS; c++) {
                rowData.put("col" + c, "v" + c)
            }

            def rootBand = new BandData(BandData.ROOT_BAND_NAME)
            rootBand.setFirstLevelBandDefinitionNames([BAND_NAME].toSet())

            def rowsIterator = new Iterator<Map<String, Object>>() {
                long produced = 0

                boolean hasNext() { produced < ROWS }

                Map<String, Object> next() {
                    produced++
                    return new HashMap<>(rowData)
                }
            }

            File outputFile = File.createTempFile("streaming-feed-large-report", ".xlsx")
            outputFile.deleteOnExit()

        when: "the document is streamed to a file while heap usage is sampled"
            def runtime = Runtime.runtime
            def peakHeap = new AtomicLong(0L)
            def sampling = new AtomicBoolean(true)
            long startNanos = System.nanoTime()

            def sampler = new Thread({
                long lastLogNanos = 0L
                while (sampling.get()) {
                    long used = runtime.totalMemory() - runtime.freeMemory()
                    peakHeap.set(Math.max(peakHeap.get(), used))
                    long now = System.nanoTime()
                    if (now - lastLogNanos >= 1_000_000_000L) {
                        lastLogNanos = now
                        log.info("progress: usedHeap={} MB, peakHeap={} MB, elapsed={} s",
                                used >> 20, peakHeap.get() >> 20, (now - startNanos).intdiv(1_000_000_000L))
                    }
                    try {
                        Thread.sleep(200L)
                    } catch (InterruptedException ignored) {
                        return
                    }
                }
            })
            sampler.daemon = true
            sampler.start()

            outputFile.withOutputStream { output ->
                def formatter = new StreamingXlsxFormatter(
                        new FormatterFactoryInput("xlsx", rootBand, template, ReportOutputType.xlsx, output))
                formatter.setStreamingBandFeed(new StreamingBandFeed(BAND_NAME, rowsIterator, rootBand))
                formatter.renderDocument()
            }
            sampling.set(false)
            long elapsedMs = (System.nanoTime() - startNanos).intdiv(1_000_000L)

            long retainedAfterGc = StreamingLargeXlsxReportGenerationTest.measureRetainedHeap(runtime)
            log.info("Rendered from feed: {} rows, elapsed={} ms, peakHeap={} MB, retainedAfterGc={} MB, output={} MB",
                    ROWS, elapsedMs, peakHeap.get() >> 20, retainedAfterGc >> 20, outputFile.length() >> 20)

            def counts = StreamingLargeXlsxReportGenerationTest.countRowsAndFirstRowCells(outputFile)

        then: "the workbook is complete and the retained heap stays within the tighter bound"
            outputFile.length() > 0
            counts.rows == ROWS
            counts.firstRowCells == COLUMNS
            retainedAfterGc < ((long) HEAP_BOUND_MB) << 20

        cleanup:
            outputFile?.delete()
    }
}
