/*
 * Copyright 2026 Haulmont.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.jmix.aitoolsflowui.model;

import io.jmix.core.entity.annotation.JmixGeneratedValue;
import io.jmix.core.entity.annotation.JmixId;
import io.jmix.core.metamodel.annotation.JmixEntity;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * One row in the AI conversation timeline. Either a persisted user/assistant
 * message, or a transient "thinking" placeholder while the assistant is
 * generating a response.
 * <p>
 * The {@code statusUpdates} list is mutable on {@link TimelineItemType#ASSISTANT_THINKING}
 * items and gets appended in-place by the controller while a background task is running.
 */
@JmixEntity
public class TimelineItem {

    @JmixId
    @JmixGeneratedValue
    private UUID id;

    private Integer type;

    private AiChatMessage message;

    private List<TimelineItemStatus> statusUpdates = new ArrayList<>();

    /**
     * Transient UI marker: {@code true} for the assistant message that was
     * just generated by the latest LLM call. Consumed (cleared by the
     * controller) right after the timeline is repainted, so the next
     * unrelated refresh does not re-animate the same row.
     */
    private Boolean fresh;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public TimelineItemType getType() {
        return type == null ? null : TimelineItemType.fromId(type);
    }

    public void setType(TimelineItemType type) {
        this.type = type == null ? null : type.getId();
    }

    public AiChatMessage getMessage() {
        return message;
    }

    public void setMessage(AiChatMessage message) {
        this.message = message;
    }

    public List<TimelineItemStatus> getStatusUpdates() {
        return statusUpdates;
    }

    public void setStatusUpdates(List<TimelineItemStatus> statusUpdates) {
        this.statusUpdates = statusUpdates;
    }

    public Boolean getFresh() {
        return fresh;
    }

    public void setFresh(Boolean fresh) {
        this.fresh = fresh;
    }
}
