/*
 * Copyright 2026 Haulmont.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.jmix.aitoolsflowui.view.chat;

/**
 * How the title of a new AI conversation is produced.
 */
public enum AiConversationTitleMode {

    /**
     * The first user message, trimmed. No model call.
     */
    FIRST_MESSAGE,

    /**
     * Generated by the model in the background; the first-message title is shown until it is ready.
     */
    GENERATED,

    /**
     * The default title is kept.
     */
    NONE
}
