/*
 * Copyright 2026 Haulmont.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.jmix.oidc.user;

import io.jmix.core.metamodel.annotation.JmixEntity;
import org.springframework.security.oauth2.core.oidc.OidcIdToken;
import org.springframework.security.oauth2.core.oidc.OidcUserInfo;
import org.springframework.security.oauth2.core.oidc.user.OidcUser;

import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.Transient;
import java.util.Map;

/**
 * Mapped superclass to be extended by JPA entity that stores user information. Extend the {@code User} entity class
 * generated by Jmix Studio in order to make it work with jmix-oidc add-on.
 */
@JmixEntity
@MappedSuperclass
public abstract class JmixOidcUserEntity implements JmixOidcUser, HasOidcUserDelegate {

    @Transient
    protected OidcUser delegate;

    public OidcUser getDelegate() {
        return delegate;
    }

    public void setDelegate(OidcUser delegate) {
        this.delegate = delegate;
    }

    @Override
    public Map<String, Object> getClaims() {
        return delegate.getClaims();
    }

    @Override
    public OidcUserInfo getUserInfo() {
        return delegate.getUserInfo();
    }

    @Override
    public OidcIdToken getIdToken() {
        return delegate.getIdToken();
    }

    @Override
    public Map<String, Object> getAttributes() {
        return delegate.getAttributes();
    }

    @Override
    public String getName() {
        return delegate.getName();
    }
}
